name: Jekyll site CI

on:
  push:
    branches: [ "protae5544-patch-1" ]  # เปลี่ยนจาก "main" เป็น "protae5544-patch-1"
  pull_request:
    branches: [ "protae5544-patch-1" ]  # เปลี่ยนจาก "main" เป็น "protae5544-patch-1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1' # Specify the Ruby version you are using

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build the site
      run: bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
